import {z} from "zod";
import { parse } from 'jsonc-parser';
require('dotenv').config();

import { generateSHA256Hash, isValidUUIDv4 } from "../utils/utils";
import { inspect } from "util";
import BaseEntityVersionImplementation, { relatedEntity } from "../implementation/sequelize/BaseEntityVersionImplementation";
import BaseEntity from "../modelsTypeScript/BaseEntity";
import { Version_Actions } from "../utils/VersionConstants";


function isBaseEntity(obj: unknown): obj is BaseEntity {
  return obj instanceof BaseEntity;
}

// Schemas

const newFUAFormatFromSchemaZod = z.object({
    // Format Data
    name: z.string(),
    content: z.string(),
    // Base Field Form Data
    codeName: z.string(),    
    versionTag: z.string(),
    versionNumber: z.number().int().positive(), // must be a positive integer
    // Audit Data
    createdBy: z.string(),
});

const editBaseEntityVersionFromSchemaZod = z.object({
    // Format Data
    uuid: z.string(),
    name: z.string(),
    content: z.string(),
    // Base Field Form Data
    codeName: z.string(),    
    versionTag: z.string(),
    versionNumber: z.number().int().positive(), // must be a positive integer
    // Audit Data
    createdBy: z.string(),
});

class BaseEntityVersionService {

    // Creation of BaseEntityVersion
    async create(        
        data : any,                         // Generic entity that comes from BaseEntity, pending to change
        type : string,                  
        action: string,
        newRelatedEntities? : Array<relatedEntity>
    ) {
        if(!isBaseEntity(data)){
            let auxError = new Error('Object received doesnt come form BaseEntity. ');
            throw auxError;
        }
        /*
        class FUAMapping extends BaseEntity{
        
        }
        */
        data = (data as BaseEntity);
        // Object Validation

        /* const result = newFUAFormatFromSchemaZod.safeParse(data);
        if( !result.success ){
            const newError = new Error('Error in BaseEntityVersion Service - create: ZOD validation. ');
            (newError as any).details = result.error;
            throw newError;
        } */
        
        // Gedatanerate Hash
        let newHash = generateSHA256Hash(JSON.stringify(data)+data.action+(process.env.HMAC_SECRET ?? 'fuagenerator'));
        
        // BaseEnitityVersion creation

        // CREATE
        // EDIT
        switch (action){
            case Version_Actions.CREATE: {
                data.updatedBy = null;
                break;
            };
            case Version_Actions.EDIT: {
                data.createdBy = data.updatedBy;
                data.updatedBy = null;
                break;
            };
            case Version_Actions.DELETE: {
                data.createdBy = data.inactiveBy;
                data.updatedBy = null;
                data.inactiveBy = null;
                break;
            };
            default: {
                break;
            }
        };

        /* // Defining the the FUA Update author as the Version creator
        returnedFUAFormat.dataValues.createdBy = returnedFUAFormat.dataValues.updatedBy;
        returnedFUAFormat.dataValues.updatedBy = null; */


        let newData = {
            ...data,
            uuidEntity: data.uuid,
            versionCounter: 1, // Hardcoded value
            type: type,
            hash: newHash,
            action: action,
            content: JSON.stringify(data,null,2),
            relatedEntities: newRelatedEntities,
        }
        // We delete id if already exists because he needs to be autogenerated by the DB
        if ((newData as any).id !== undefined) {
            delete (newData as any).id;
        }
        //We do the same for the uuid
        if ((newData as any).uuid !== undefined) {
            delete (newData as any).uuid;
        }

        let newVersion = null;
        try {
            newVersion = await BaseEntityVersionImplementation.createSequelize(newData);
        } catch (err: any){
            (err as Error).message = 'Error in BaseEntityVersion Service: ' + (err as Error).message;
            const long = inspect(err, { depth: 10, colors: false });
            (err as any).details = (err as any).details ?? long;
            throw err;
        }

        return {
            uuid: newVersion.uuid
        };
    };

    // List Base Enitties Versions
    // Pending to paginate results
    async listAll( ) {
        let returnedVersions = null;
        try {
            returnedVersions = await BaseEntityVersionImplementation.listAllSequelize();

        } catch (err: any){
            (err as Error).message =  'Error in FUA Format From Schema Service: ' + (err as Error).message;
            throw err;
        }        

        return returnedVersions;
    }; 

    // Get BaseEntityVersion by Id (Id or UUID)
    async getByIdOrUUID( data: {
            id: string; 
            type: string;
        } ) {
        let returnedFUAFormat = null;

        // Check if UUID or Id was sent
        let id = null;
        const nuNumber = Number(data.id);
        if( Number.isInteger(nuNumber) ){
            id = nuNumber;

            try {
                returnedFUAFormat = await BaseEntityVersionImplementation.getByIdSequelize(id, data.type);

            } catch (err: unknown){
                (err as Error).message =  'Error in FUA Format From SchemaFUA Format From Schema Service: ' + (err as Error).message;
                throw err;
            }     
        }else{
            // Get id by UUID
            //Validate UUID Format        
            if (!isValidUUIDv4(data.id) ) {
                throw new Error("Error in FUA Format From Schema Service: Invalid UUID format. ");
            }
            try {

                returnedFUAFormat = await BaseEntityVersionImplementation.getByUUIDSequelize(data.id, data.type);

            } catch (err: unknown){
                (err as Error).message =  'Error in FUA Format From Schema Service: ' + (err as Error).message;
                throw err;
            }
            
        }      
        // If nothing was offund, return a null
        return returnedFUAFormat;
    };

    // List Base Enitties Versions
    // Pending to paginate results
    async listVersions( data: {
        uuid: string; 
        type: string;
    }) {
        let returnedVersions = [];
        // Check for existing versions of this object

        // Get id by UUID
        //Validate UUID Format        
        if (!isValidUUIDv4(data.uuid) ) {
            throw new Error("Error in FUA Format From Schema Service: Invalid UUID format. ");
        }
        try {

            returnedVersions = await BaseEntityVersionImplementation.getVersionsByUUID(data);

        } catch (err: unknown){
            (err as Error).message =  'Error in FUA Format From Schema Service: ' + (err as Error).message;
            throw err;
        }

        return returnedVersions;
    };
};

export default new BaseEntityVersionService();
