export {
    type VisitPayload,
    type PatientDetails,
    type Ipress,
    type AseguradoSis,
    type CondicionPaciente,
    type Hospitalizacion,
    type Referencia,
    type ResponsableAtencion,
    type Diagnostico,
    type Medicamento,
    type Insumo,
    type Procedimiento,
    type SubComponentePrestacional,
    type FuaBlock,
    VisitPayloadSchema,
    PatientDetailsSchema,
    IpressSchema,
    AseguradoSisSchema,
    CondicionPacienteSchema,
    HospitalizacionSchema,
    ReferenciaSchema,
    ResponsableAtencionSchema,
    DiagnosticoSchema,
    MedicamentoSchema,
    InsumoSchema,
    ProcedimientoSchema,
    SubComponentePrestacionalSchema,
    FuaBlockSchema,
    DESTINOS_ASEGURADO,
} from "./visitPayload";

export {
    EdadCalculada,
    ValidationContext,
    type ValidationContextData,
    ValidationContextSchema,
} from "./context";

export {
    type RuleResult,
    type ValidationResult,
    RuleResultSchema,
    ValidationResultSchema,
    RULE_ACTIONS,
    createRuleResult,
    createEmptyValidationResult,
    consolidateResults,
} from "./results";